language: csharp
solution: Skelvy.sln
mono: none
sudo: required
dist: xenial
dotnet: 3.1

install:
  - dotnet restore

script:
  - dotnet build src/Skelvy.WebAPI
  - dotnet test test/Skelvy.Domain.Test
  - dotnet test test/Skelvy.Application.Test
