language: csharp
solution: Skelvy.sln
mono: none
sudo: required
dist: xenial
dotnet: 2.2

install:
  - dotnet restore

script:
  - dotnet build Skelvy.WebAPI
  - dotnet test Skelvy.Domain.Test
  - dotnet test Skelvy.Application.Test
