version: '3'

services:

  api:
    container_name: "skelvy-dotnet"
    image: "skelvy:latest"
    build:
      context: .
      dockerfile: "src/Skelvy.WebAPI/Dockerfile"
    depends_on:
      - mssql
      - redis
    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "ASPNETCORE_URLS=http://0.0.0.0:80"
      - "ConnectionStrings__Database=Server=mssql; Database=skelvy; MultipleActiveResultSets=true; User Id=sa; Password=zaq1@WSX;"
      - "ConnectionStrings__Redis=redis:6379"
    ports:
      - "80:80"

  mssql:
    container_name: "skelvy-mssql"
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "zaq1@WSX"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  redis:
    container_name: "skelvy-redis"
    image: "redis:latest"
    ports:
      - "6379:6379"
