version: '3'

services:

  mssql:
    container_name: "skelvy-mssql"
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "zaq1@WSX"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  redis:
    container_name: "skelvy-redis"
    image: "redis:latest"
    ports:
      - "6381:6379"
