// <auto-generated />
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Skelvy.Persistence.Migrations
{
    public partial class DrinkTypesInsteadOfDrinks : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Meetings_Drinks_DrinkId",
                table: "Meetings");

            migrationBuilder.DropTable(
                name: "MeetingRequestDrinks");

            migrationBuilder.DropTable(
                name: "Drinks");

            migrationBuilder.DropIndex(
                name: "IX_Meetings_DrinkId",
                table: "Meetings");

            migrationBuilder.AddColumn<int>(
                name: "DrinkTypeId",
                table: "Meetings",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "DrinkTypes",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DrinkTypes", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "MeetingRequestDrinkTypes",
                columns: table => new
                {
                    MeetingRequestId = table.Column<int>(nullable: false),
                    DrinkTypeId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MeetingRequestDrinkTypes", x => new { x.MeetingRequestId, x.DrinkTypeId });
                    table.ForeignKey(
                        name: "FK_MeetingRequestDrinkTypes_DrinkTypes_DrinkTypeId",
                        column: x => x.DrinkTypeId,
                        principalTable: "DrinkTypes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_MeetingRequestDrinkTypes_MeetingRequests_MeetingRequestId",
                        column: x => x.MeetingRequestId,
                        principalTable: "MeetingRequests",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Meetings_DrinkTypeId",
                table: "Meetings",
                column: "DrinkTypeId");

            migrationBuilder.CreateIndex(
                name: "IX_DrinkTypes_Name",
                table: "DrinkTypes",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_MeetingRequestDrinkTypes_DrinkTypeId",
                table: "MeetingRequestDrinkTypes",
                column: "DrinkTypeId");

            migrationBuilder.AddForeignKey(
                name: "FK_Meetings_DrinkTypes_DrinkTypeId",
                table: "Meetings",
                column: "DrinkTypeId",
                principalTable: "DrinkTypes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Meetings_DrinkTypes_DrinkTypeId",
                table: "Meetings");

            migrationBuilder.DropTable(
                name: "MeetingRequestDrinkTypes");

            migrationBuilder.DropTable(
                name: "DrinkTypes");

            migrationBuilder.DropIndex(
                name: "IX_Meetings_DrinkTypeId",
                table: "Meetings");

            migrationBuilder.DropColumn(
                name: "DrinkTypeId",
                table: "Meetings");

            migrationBuilder.CreateTable(
                name: "Drinks",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Drinks", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "MeetingRequestDrinks",
                columns: table => new
                {
                    MeetingRequestId = table.Column<int>(nullable: false),
                    DrinkId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MeetingRequestDrinks", x => new { x.MeetingRequestId, x.DrinkId });
                    table.ForeignKey(
                        name: "FK_MeetingRequestDrinks_Drinks_DrinkId",
                        column: x => x.DrinkId,
                        principalTable: "Drinks",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_MeetingRequestDrinks_MeetingRequests_MeetingRequestId",
                        column: x => x.MeetingRequestId,
                        principalTable: "MeetingRequests",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Meetings_DrinkId",
                table: "Meetings",
                column: "DrinkId");

            migrationBuilder.CreateIndex(
                name: "IX_Drinks_Name",
                table: "Drinks",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_MeetingRequestDrinks_DrinkId",
                table: "MeetingRequestDrinks",
                column: "DrinkId");

            migrationBuilder.AddForeignKey(
                name: "FK_Meetings_Drinks_DrinkId",
                table: "Meetings",
                column: "DrinkId",
                principalTable: "Drinks",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
