// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Skelvy.Persistence.Migrations
{
  [DbContext(typeof(SkelvyContext))]
  partial class SkelvyContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
        .HasAnnotation("Relational:MaxIdentifierLength", 128)
        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity("Skelvy.Domain.Entities.User", b =>
      {
        b.Property<int>("Id")
          .ValueGeneratedOnAdd()
          .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        b.Property<string>("Email")
          .IsRequired()
          .HasMaxLength(60);

        b.Property<string>("Name")
          .IsRequired()
          .HasMaxLength(60);

        b.HasKey("Id");

        b.ToTable("Users");
      });
#pragma warning restore 612, 618
    }
  }
}
